// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace CodexSystem
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct CodexRoot : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_25_2_10(); }
  public static CodexRoot GetRootAsCodexRoot(ByteBuffer _bb) { return GetRootAsCodexRoot(_bb, new CodexRoot()); }
  public static CodexRoot GetRootAsCodexRoot(ByteBuffer _bb, CodexRoot obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public static bool VerifyCodexRoot(ByteBuffer _bb) {Google.FlatBuffers.Verifier verifier = new Google.FlatBuffers.Verifier(_bb); return verifier.VerifyBuffer("", false, CodexRootVerify.Verify); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public CodexRoot __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public CodexSystem.Category? Categories(int j) { int o = __p.__offset(4); return o != 0 ? (CodexSystem.Category?)(new CodexSystem.Category()).__assign(__p.__indirect(__p.__vector(o) + j * 4), __p.bb) : null; }
  public int CategoriesLength { get { int o = __p.__offset(4); return o != 0 ? __p.__vector_len(o) : 0; } }
  public CodexSystem.Resource? Resources(int j) { int o = __p.__offset(6); return o != 0 ? (CodexSystem.Resource?)(new CodexSystem.Resource()).__assign(__p.__indirect(__p.__vector(o) + j * 4), __p.bb) : null; }
  public int ResourcesLength { get { int o = __p.__offset(6); return o != 0 ? __p.__vector_len(o) : 0; } }

  public static Offset<CodexSystem.CodexRoot> CreateCodexRoot(FlatBufferBuilder builder,
      VectorOffset categoriesOffset = default(VectorOffset),
      VectorOffset resourcesOffset = default(VectorOffset)) {
    builder.StartTable(2);
    CodexRoot.AddResources(builder, resourcesOffset);
    CodexRoot.AddCategories(builder, categoriesOffset);
    return CodexRoot.EndCodexRoot(builder);
  }

  public static void StartCodexRoot(FlatBufferBuilder builder) { builder.StartTable(2); }
  public static void AddCategories(FlatBufferBuilder builder, VectorOffset categoriesOffset) { builder.AddOffset(0, categoriesOffset.Value, 0); }
  public static VectorOffset CreateCategoriesVector(FlatBufferBuilder builder, Offset<CodexSystem.Category>[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
  public static VectorOffset CreateCategoriesVectorBlock(FlatBufferBuilder builder, Offset<CodexSystem.Category>[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateCategoriesVectorBlock(FlatBufferBuilder builder, ArraySegment<Offset<CodexSystem.Category>> data) { builder.StartVector(4, data.Count, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateCategoriesVectorBlock(FlatBufferBuilder builder, IntPtr dataPtr, int sizeInBytes) { builder.StartVector(1, sizeInBytes, 1); builder.Add<Offset<CodexSystem.Category>>(dataPtr, sizeInBytes); return builder.EndVector(); }
  public static void StartCategoriesVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static void AddResources(FlatBufferBuilder builder, VectorOffset resourcesOffset) { builder.AddOffset(1, resourcesOffset.Value, 0); }
  public static VectorOffset CreateResourcesVector(FlatBufferBuilder builder, Offset<CodexSystem.Resource>[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
  public static VectorOffset CreateResourcesVectorBlock(FlatBufferBuilder builder, Offset<CodexSystem.Resource>[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateResourcesVectorBlock(FlatBufferBuilder builder, ArraySegment<Offset<CodexSystem.Resource>> data) { builder.StartVector(4, data.Count, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateResourcesVectorBlock(FlatBufferBuilder builder, IntPtr dataPtr, int sizeInBytes) { builder.StartVector(1, sizeInBytes, 1); builder.Add<Offset<CodexSystem.Resource>>(dataPtr, sizeInBytes); return builder.EndVector(); }
  public static void StartResourcesVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static Offset<CodexSystem.CodexRoot> EndCodexRoot(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<CodexSystem.CodexRoot>(o);
  }
  public static void FinishCodexRootBuffer(FlatBufferBuilder builder, Offset<CodexSystem.CodexRoot> offset) { builder.Finish(offset.Value); }
  public static void FinishSizePrefixedCodexRootBuffer(FlatBufferBuilder builder, Offset<CodexSystem.CodexRoot> offset) { builder.FinishSizePrefixed(offset.Value); }
}


static public class CodexRootVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyVectorOfTables(tablePos, 4 /*Categories*/, CodexSystem.CategoryVerify.Verify, false)
      && verifier.VerifyVectorOfTables(tablePos, 6 /*Resources*/, CodexSystem.ResourceVerify.Verify, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
