// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace CodexSystem
{

public enum EntryType : sbyte
{
  Primary = 0,
  Secondary = 1,
};


}
