// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace CodexSystem
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct Entry : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_25_2_10(); }
  public static Entry GetRootAsEntry(ByteBuffer _bb) { return GetRootAsEntry(_bb, new Entry()); }
  public static Entry GetRootAsEntry(ByteBuffer _bb, Entry obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public Entry __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public uint Id { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetUint(o + __p.bb_pos) : (uint)0; } }
  public uint RequirementId { get { int o = __p.__offset(6); return o != 0 ? __p.bb.GetUint(o + __p.bb_pos) : (uint)0; } }
  public CodexSystem.EntryType EntryType { get { int o = __p.__offset(8); return o != 0 ? (CodexSystem.EntryType)__p.bb.GetSbyte(o + __p.bb_pos) : CodexSystem.EntryType.Primary; } }
  public string Title { get { int o = __p.__offset(10); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetTitleBytes() { return __p.__vector_as_span<byte>(10, 1); }
#else
  public ArraySegment<byte>? GetTitleBytes() { return __p.__vector_as_arraysegment(10); }
#endif
  public byte[] GetTitleArray() { return __p.__vector_as_array<byte>(10); }
  public string Content { get { int o = __p.__offset(12); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetContentBytes() { return __p.__vector_as_span<byte>(12, 1); }
#else
  public ArraySegment<byte>? GetContentBytes() { return __p.__vector_as_arraysegment(12); }
#endif
  public byte[] GetContentArray() { return __p.__vector_as_array<byte>(12); }
  public uint AudioId { get { int o = __p.__offset(14); return o != 0 ? __p.bb.GetUint(o + __p.bb_pos) : (uint)0; } }
  public uint ImageId { get { int o = __p.__offset(16); return o != 0 ? __p.bb.GetUint(o + __p.bb_pos) : (uint)0; } }
  public int SortOrder { get { int o = __p.__offset(18); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public CodexSystem.Entry? SubEntries(int j) { int o = __p.__offset(20); return o != 0 ? (CodexSystem.Entry?)(new CodexSystem.Entry()).__assign(__p.__indirect(__p.__vector(o) + j * 4), __p.bb) : null; }
  public int SubEntriesLength { get { int o = __p.__offset(20); return o != 0 ? __p.__vector_len(o) : 0; } }

  public static Offset<CodexSystem.Entry> CreateEntry(FlatBufferBuilder builder,
      uint id = 0,
      uint requirement_id = 0,
      CodexSystem.EntryType entry_type = CodexSystem.EntryType.Primary,
      StringOffset titleOffset = default(StringOffset),
      StringOffset contentOffset = default(StringOffset),
      uint audio_id = 0,
      uint image_id = 0,
      int sort_order = 0,
      VectorOffset sub_entriesOffset = default(VectorOffset)) {
    builder.StartTable(9);
    Entry.AddSubEntries(builder, sub_entriesOffset);
    Entry.AddSortOrder(builder, sort_order);
    Entry.AddImageId(builder, image_id);
    Entry.AddAudioId(builder, audio_id);
    Entry.AddContent(builder, contentOffset);
    Entry.AddTitle(builder, titleOffset);
    Entry.AddRequirementId(builder, requirement_id);
    Entry.AddId(builder, id);
    Entry.AddEntryType(builder, entry_type);
    return Entry.EndEntry(builder);
  }

  public static void StartEntry(FlatBufferBuilder builder) { builder.StartTable(9); }
  public static void AddId(FlatBufferBuilder builder, uint id) { builder.AddUint(0, id, 0); }
  public static void AddRequirementId(FlatBufferBuilder builder, uint requirementId) { builder.AddUint(1, requirementId, 0); }
  public static void AddEntryType(FlatBufferBuilder builder, CodexSystem.EntryType entryType) { builder.AddSbyte(2, (sbyte)entryType, 0); }
  public static void AddTitle(FlatBufferBuilder builder, StringOffset titleOffset) { builder.AddOffset(3, titleOffset.Value, 0); }
  public static void AddContent(FlatBufferBuilder builder, StringOffset contentOffset) { builder.AddOffset(4, contentOffset.Value, 0); }
  public static void AddAudioId(FlatBufferBuilder builder, uint audioId) { builder.AddUint(5, audioId, 0); }
  public static void AddImageId(FlatBufferBuilder builder, uint imageId) { builder.AddUint(6, imageId, 0); }
  public static void AddSortOrder(FlatBufferBuilder builder, int sortOrder) { builder.AddInt(7, sortOrder, 0); }
  public static void AddSubEntries(FlatBufferBuilder builder, VectorOffset subEntriesOffset) { builder.AddOffset(8, subEntriesOffset.Value, 0); }
  public static VectorOffset CreateSubEntriesVector(FlatBufferBuilder builder, Offset<CodexSystem.Entry>[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
  public static VectorOffset CreateSubEntriesVectorBlock(FlatBufferBuilder builder, Offset<CodexSystem.Entry>[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateSubEntriesVectorBlock(FlatBufferBuilder builder, ArraySegment<Offset<CodexSystem.Entry>> data) { builder.StartVector(4, data.Count, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateSubEntriesVectorBlock(FlatBufferBuilder builder, IntPtr dataPtr, int sizeInBytes) { builder.StartVector(1, sizeInBytes, 1); builder.Add<Offset<CodexSystem.Entry>>(dataPtr, sizeInBytes); return builder.EndVector(); }
  public static void StartSubEntriesVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static Offset<CodexSystem.Entry> EndEntry(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<CodexSystem.Entry>(o);
  }
}


static public class EntryVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyField(tablePos, 4 /*Id*/, 4 /*uint*/, 4, false)
      && verifier.VerifyField(tablePos, 6 /*RequirementId*/, 4 /*uint*/, 4, false)
      && verifier.VerifyField(tablePos, 8 /*EntryType*/, 1 /*CodexSystem.EntryType*/, 1, false)
      && verifier.VerifyString(tablePos, 10 /*Title*/, false)
      && verifier.VerifyString(tablePos, 12 /*Content*/, false)
      && verifier.VerifyField(tablePos, 14 /*AudioId*/, 4 /*uint*/, 4, false)
      && verifier.VerifyField(tablePos, 16 /*ImageId*/, 4 /*uint*/, 4, false)
      && verifier.VerifyField(tablePos, 18 /*SortOrder*/, 4 /*int*/, 4, false)
      && verifier.VerifyVectorOfTables(tablePos, 20 /*SubEntries*/, CodexSystem.EntryVerify.Verify, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
