// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace CodexSystem
{

public enum ResourceType : sbyte
{
  None = 0,
  Audio = 1,
  Image = 2,
};


}
