// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace CodexSystem
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct Resource : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_25_2_10(); }
  public static Resource GetRootAsResource(ByteBuffer _bb) { return GetRootAsResource(_bb, new Resource()); }
  public static Resource GetRootAsResource(ByteBuffer _bb, Resource obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public Resource __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public uint Id { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetUint(o + __p.bb_pos) : (uint)0; } }
  public string FilePath { get { int o = __p.__offset(6); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetFilePathBytes() { return __p.__vector_as_span<byte>(6, 1); }
#else
  public ArraySegment<byte>? GetFilePathBytes() { return __p.__vector_as_arraysegment(6); }
#endif
  public byte[] GetFilePathArray() { return __p.__vector_as_array<byte>(6); }
  public CodexSystem.ResourceType ResourceType { get { int o = __p.__offset(8); return o != 0 ? (CodexSystem.ResourceType)__p.bb.GetSbyte(o + __p.bb_pos) : CodexSystem.ResourceType.None; } }

  public static Offset<CodexSystem.Resource> CreateResource(FlatBufferBuilder builder,
      uint id = 0,
      StringOffset file_pathOffset = default(StringOffset),
      CodexSystem.ResourceType resource_type = CodexSystem.ResourceType.None) {
    builder.StartTable(3);
    Resource.AddFilePath(builder, file_pathOffset);
    Resource.AddId(builder, id);
    Resource.AddResourceType(builder, resource_type);
    return Resource.EndResource(builder);
  }

  public static void StartResource(FlatBufferBuilder builder) { builder.StartTable(3); }
  public static void AddId(FlatBufferBuilder builder, uint id) { builder.AddUint(0, id, 0); }
  public static void AddFilePath(FlatBufferBuilder builder, StringOffset filePathOffset) { builder.AddOffset(1, filePathOffset.Value, 0); }
  public static void AddResourceType(FlatBufferBuilder builder, CodexSystem.ResourceType resourceType) { builder.AddSbyte(2, (sbyte)resourceType, 0); }
  public static Offset<CodexSystem.Resource> EndResource(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<CodexSystem.Resource>(o);
  }
}


static public class ResourceVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyField(tablePos, 4 /*Id*/, 4 /*uint*/, 4, false)
      && verifier.VerifyString(tablePos, 6 /*FilePath*/, false)
      && verifier.VerifyField(tablePos, 8 /*ResourceType*/, 1 /*CodexSystem.ResourceType*/, 1, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
